"""
Predictive Maintenance Agent: Autonomous Triage, Root-Cause Diagnosis, and Work Order Generation.
"""

import logging
from dataclasses import asdict, dataclass
from typing import Dict, List, Optional
import pandas as pd

from src.config import (
    HDF_SPEED_THRESHOLD,
    HDF_TEMP_DIFF_THRESHOLD,
    OSF_STRAIN_THRESHOLDS,
    PWF_MAX_WATTS,
    PWF_MIN_WATTS,
    TWF_WEAR_MINUTES,
)

logger = logging.getLogger(__name__)


@dataclass
class MaintenanceTicket:
    """Structured actionable maintenance work order generated by the agent."""
    ticket_id: str
    timestamp: str
    equipment_id: str
    product_type: str
    risk_tier: str
    health_score: float
    failure_probability_pct: float
    anomaly_score_pct: float
    diagnosed_failure_mode: str
    root_cause_explanation: str
    recommended_action: str
    urgency_level: str
    top_contributing_factors: str = ""


class PredictiveMaintenanceAgent:
    """
    Autonomous intelligence layer that ingests telemetry, ML failure predictions,
    and anomaly scores to perform root-cause triage and issue prescriptive work orders.
    """

    def __init__(self):
        self.ticket_counter = 0

    def compute_health_and_risk(
        self,
        failure_prob_pct: float,
        anomaly_score_pct: float,
    ) -> tuple[float, str]:
        """
        Synthesize combined machine health index (0–100%) and risk tier.
        Health decreases with either high failure likelihood or high anomaly score.
        """
        composite_risk = max(failure_prob_pct, anomaly_score_pct * 0.85)
        health_score = max(0.0, min(100.0, 100.0 - composite_risk))

        if composite_risk >= 75.0:
            risk_tier = "CRITICAL"
        elif composite_risk >= 50.0:
            risk_tier = "WARNING"
        elif composite_risk >= 25.0:
            risk_tier = "WATCH"
        else:
            risk_tier = "NORMAL"

        return round(health_score, 1), risk_tier

    def diagnose_root_cause(self, row: pd.Series) -> tuple[str, str, str, str]:
        """
        Rule-grounded physical diagnostics based on telemetry indicators.
        Returns: (diagnosed_mode, root_cause_explanation, recommended_action, urgency_level)
        """
        product_type = str(row.get("product_type", "L"))
        temp_diff = float(row.get("temp_diff_k", row.get("process_temp_k", 300) - row.get("air_temp_k", 290)))
        speed = float(row.get("rotational_speed_rpm", 1500))
        power = float(row.get("power_watts", 4500))
        tool_wear = float(row.get("tool_wear_min", 0))
        torque = float(row.get("torque_nm", 40))
        strain = float(row.get("strain_index", tool_wear * torque))

        osf_limit = OSF_STRAIN_THRESHOLDS.get(product_type, 11000.0)

        # 1. Heat Dissipation Failure (HDF)
        if temp_diff < HDF_TEMP_DIFF_THRESHOLD and speed < HDF_SPEED_THRESHOLD:
            return (
                "HDF - Heat Dissipation Failure",
                f"Thermal differential between process and ambient is only {temp_diff:.2f}K (limit < {HDF_TEMP_DIFF_THRESHOLD}K) combined with low fan/spindle speed ({speed:.0f} RPM). Heat is accumulating rapidly.",
                "Inspect radiator fins for debris, test coolant circulation pump, and check cooling fan motor.",
                "HIGH (Address within 8-12 hours)",
            )

        # 2. Power Failure (PWF)
        if power < PWF_MIN_WATTS or power > PWF_MAX_WATTS:
            return (
                "PWF - Power Failure",
                f"Mechanical shaft power consumption is {power:.1f}W, operating outside nominal safe window [{PWF_MIN_WATTS}W, {PWF_MAX_WATTS}W]. Indicates severe electrical drive defect or mechanical seizure.",
                "Conduct motor inverter electrical inspection, measure phase resistance, and check power supply voltage.",
                "IMMEDIATE (Halt operation / inspect before restart)",
            )

        # 3. Overstrain Failure (OSF)
        if strain > osf_limit:
            return (
                "OSF - Overstrain Failure",
                f"Combined mechanical load strain ({strain:.0f}) exceeds type-{product_type} stress limit ({osf_limit:.0f}). Heavy torque on worn tooling threatens spindle shaft integrity.",
                "Reduce feed rate and cutting depth immediately; replace tooling assembly and inspect chuck clamp.",
                "IMMEDIATE (Risk of mechanical fracture)",
            )

        # 4. Tool Wear Failure (TWF)
        if tool_wear >= TWF_WEAR_MINUTES:
            return (
                "TWF - Tool Wear Failure",
                f"Cumulative tool wear reached {tool_wear:.0f} min (safe operating threshold: {TWF_WEAR_MINUTES:.0f} min). High probability of surface finish degradation and micro-fractures.",
                "Schedule tooling replacement during next cycle pause. Inspect tool holder for wear marks.",
                "MEDIUM (Schedule tool replacement)",
            )

        # 5. Multivariate / Sensor Anomaly
        return (
            "ANOMALY - Multivariate Mechanical Drift",
            "Multiple telemetry signals exhibit atypical cross-correlation detected by the Isolation Forest engine (unusual torque/speed variance ratio).",
            "Perform vibration analysis, check drive belt tension, and verify sensor calibration on spindle.",
            "LOW-MEDIUM (Routine preventive inspection)",
        )

    def evaluate_reading(
        self,
        row: pd.Series,
        shap_factors: Optional[List[tuple]] = None,
    ) -> Optional[MaintenanceTicket]:
        """
        Evaluate a single telemetry point.
        If risk tier is WATCH, WARNING, or CRITICAL, generates a formal MaintenanceTicket.
        """
        fail_prob = float(row.get("failure_probability_pct", 0.0))
        anomaly_score = float(row.get("anomaly_score_pct", 0.0))

        health_score, risk_tier = self.compute_health_and_risk(fail_prob, anomaly_score)

        if risk_tier == "NORMAL":
            return None

        self.ticket_counter += 1
        product_id = str(row.get("product_id", f"MACH-{int(row.get('udi', 0)):04d}"))
        timestamp = str(row.get("timestamp", "2026-01-01 00:00:00"))
        product_type = str(row.get("product_type", "L"))

        mode, explanation, action, urgency = self.diagnose_root_cause(row)

        formatted_shap = ""
        if shap_factors:
            formatted_shap = ", ".join([f"{k} ({'+' if v >= 0 else ''}{v:.2f})" for k, v in shap_factors])

        ticket = MaintenanceTicket(
            ticket_id=f"TICK-{self.ticket_counter:05d}",
            timestamp=timestamp,
            equipment_id=product_id,
            product_type=product_type,
            risk_tier=risk_tier,
            health_score=health_score,
            failure_probability_pct=round(fail_prob, 1),
            anomaly_score_pct=round(anomaly_score, 1),
            diagnosed_failure_mode=mode,
            root_cause_explanation=explanation,
            recommended_action=action,
            urgency_level=urgency,
            top_contributing_factors=formatted_shap,
        )
        return ticket

    def batch_evaluate(self, df: pd.DataFrame) -> List[MaintenanceTicket]:
        """Evaluate an entire telemetry DataFrame and return all generated tickets."""
        tickets: List[MaintenanceTicket] = []
        for _, row in df.iterrows():
            ticket = self.evaluate_reading(row)
            if ticket is not None:
                tickets.append(ticket)
        logger.info(f"Agent evaluated {len(df)} records -> Generated {len(tickets)} maintenance tickets.")
        return tickets
